// utils/dataFake/resources.ts

const resources = [
  {
    id: 1,
    name: "Wireless Keyboard",
    description: "A sleek and modern wireless keyboard with long battery life.",
    features: ["Bluetooth connectivity", "Rechargeable battery", "Compact design"],
    category: "Electronics",
    size: 150,
    available: true,
    saleAvailability: true,
    price: 49.99,
    cost: 25.0,
    image: "https://example.com/images/wireless-keyboard.jpg",
  },
  {
    id: 2,
    name: "Ergonomic Chair",
    description: "An ergonomic office chair designed for long hours of comfort.",
    features: ["Adjustable height", "Lumbar support", "Breathable mesh back"],
    category: "Furniture",
    size: 20,
    available: true,
    saleAvailability: false,
    price: 199.99,
    cost: 120.0,
    image: "https://example.com/images/ergonomic-chair.jpg",
  },
  {
    id: 3,
    name: "Pack of A4 Paper (500 sheets)",
    description: "High-quality A4 paper suitable for printing and writing.",
    features: ["100% recyclable", "80gsm thickness", "Bright white"],
    category: "Office Supplies",
    size: 500,
    available: false,
    saleAvailability: false,
    price: 5.99,
    cost: 3.0,
    image: "https://example.com/images/a4-paper-pack.jpg",
  },
  {
    id: 4,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 5,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 6,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 7,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 8,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 9,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 10,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 11,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 12,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 13,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 14,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 15,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },


  {
    id: 16,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },{
    id: 17,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },

  {
    id: 18,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 19,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 20,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },

  {
    id: 21,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 22,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 23,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 24,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },
  {
    id: 25,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },{
    id: 26,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  },

  {
    id: 27,
    name: "24-inch Monitor",
    description: "A high-definition monitor with vibrant colors and a slim design.",
    features: ["1920x1080 resolution", "HDMI and DisplayPort", "Anti-glare screen"],
    category: "Electronics",
    size: 50,
    available: true,
    saleAvailability: true,
    price: 149.99,
    cost: 100.0,
    image: "https://example.com/images/24-inch-monitor.jpg",
  }
];

export default resources;